Remove DM e2e tests from CI

diff --git a/.github/workflows/e2e-mac.yml b/.github/workflows/e2e-mac.yml
--- a/.github/workflows/e2e-mac.yml
+++ b/.github/workflows/e2e-mac.yml
@@ -63,10 +63,12 @@ jobs:
         run: hdiutil mount $FILE_NAME
 
       - name: Add App file to applications
+        id: finish-build
         run: cd ~ && cp -R "/Volumes/Quiet $VERSION${{matrix.binary_suffix}}/Quiet.app" /Applications
 
       - name: Run one client test
         uses: nick-fields/retry@14672906e672a08bd6eeb15720e9ed3ce869cdd4 # v2.9.0
+        if: (success() || failure()) && steps.finish-build.outcome == 'success'
         with:
           timeout_minutes: 15
           max_attempts: 3
@@ -74,6 +76,7 @@ jobs:
 
       - name: Run user profile test
         uses: nick-fields/retry@14672906e672a08bd6eeb15720e9ed3ce869cdd4 # v2.9.0
+        if: (success() || failure()) && steps.finish-build.outcome == 'success'
         with:
           timeout_minutes: 25
           max_attempts: 3
@@ -81,6 +84,7 @@ jobs:
 
       - name: Run multiple clients test
         uses: nick-fields/retry@14672906e672a08bd6eeb15720e9ed3ce869cdd4 # v2.9.0
+        if: (success() || failure()) && steps.finish-build.outcome == 'success'
         with:
           timeout_minutes: 25
           max_attempts: 3
@@ -88,20 +92,23 @@ jobs:
       
       - name: Run multiple clients test (private channels)
         uses: nick-fields/retry@14672906e672a08bd6eeb15720e9ed3ce869cdd4 # v2.9.0
+        if: (success() || failure()) && steps.finish-build.outcome == 'success'
         with:
           timeout_minutes: 25
           max_attempts: 3
           command: cd packages/e2e-tests && npm run test multipleClients.privateChannels.test.ts
 
-      - name: Run multiple clients test (DMs)
-        uses: nick-fields/retry@14672906e672a08bd6eeb15720e9ed3ce869cdd4 # v2.9.0
-        with:
-          timeout_minutes: 25
-          max_attempts: 3
-          command: cd packages/e2e-tests && npm run test multipleClients.dms.test.ts
+      # - name: Run multiple clients test (DMs)
+      #   uses: nick-fields/retry@14672906e672a08bd6eeb15720e9ed3ce869cdd4 # v2.9.0
+      #   if: (success() || failure()) && steps.finish-build.outcome == 'success'
+      #   with:
+      #     timeout_minutes: 25
+      #     max_attempts: 3
+      #     command: cd packages/e2e-tests && npm run test multipleClients.dms.test.ts
 
       - name: Run invitation link test - Includes 2 separate application clients
         uses: nick-fields/retry@14672906e672a08bd6eeb15720e9ed3ce869cdd4 # v2.9.0
+        if: (success() || failure()) && steps.finish-build.outcome == 'success'
         with:
           timeout_minutes: 25
           max_attempts: 3
